scheduler_transformations:
  outputs:
    dev:
      dbname: mage_db
      host: postgres
      pass: root
      port: 5432
      threads: 4
      type: postgres
      user: root
      schema: analytics
  target: dev
